site_name: Quantum Information & Computation Lab
site_description: 專注於量子導引、量子資源理論與古典陰影的實驗室
site_author: Lab Admin
site_url: https://gyosei8329.github.io/Lab-website/

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/logo.png

  font:
    text: Noto Sans TC
    code: JetBrains Mono

  features:
    - content.tabs.link
    - content.tabs.reveal
    - header.autohide
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - toc.integrate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: change to dark theme

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: change to light theme

extra:
  alternate:
    - name: 繁體中文
      link: /
      lang: zh
    - name: English
      link: /en/
      lang: en

plugins:
  - search
  - i18n:
      languages:
        - locale: zh
          name: 繁體中文
          default: true
        - locale: en
          name: English
          nav_translations:
            首頁: Home
            團隊成員: Team
            現任成員: Current Members
            歷屆系友: Alumni
            研究介紹: Research
            論文發表: Publications
            聯絡我們: Contact Us
  - bibtex:
      bib_file: "docs/publications.bib"

nav:
  - 首頁: index.md
  - 團隊成員: member.md
  - 研究介紹: research.md
  - 論文發表: publications.md
  - 聯絡我們: contact.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - pymdownx.superfences
  - pymdownx.details
  - md_in_html
  - footnotes
  - def_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - assets/stylesheets/home.css
  - assets/stylesheets/members.css

extra_javascript:
  - assets/javascripts/custom.js
